version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web.dockerfile
        volumes:
            - ./:/var/www
        environment:
            VIRTUAL_HOST: simon.dev.dzh.hamburg
    app:
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        volumes:
            - ./:/var/www
    composer:
        image: composer/composer
        volumes_from: 
            - web
        working_dir: /var/www

networks:
    default:
        external:
            name: nginx-proxy
