version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "8001:80"
    app:
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        volumes:
            - ./:/var/www
    composer:
        image: composer/composer
        volumes_from: 
            - web
        working_dir: /var/www